replicaCount: 1

image:
  repository: 478879297284.dkr.ecr.us-east-1.amazonaws.com/catalog-service
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-secret

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 60

readinessProbe:
  path: /actuator/health/readiness
  port: 8080
  initialDelaySeconds: 30

envFrom:
  - secretRef:
      name: db-credentials

configmap:
  SPRING_DATASOURCE_URL: jdbc:postgresql://pharma-dev-postgres.c8zsguwge5o7.us-east-1.rds.amazonaws.com:5432/pharmadb


